name: Update README
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: SYL
          max_post_count: "5"
          feed_list: "https://rsshub.app/lanqiao/courses/%E5%85%A8%E9%83%A8"
